language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install
before_script:
- cp themes/hiero.config/_config.yml themes/hiero/
- git config --global user.name 'xiaming.chen'
- git config --global user.email 'chenxm35@gmail.com'
- sed -i'' "s~git@github.com:caesar0301/caesar0301.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/caesar0301/caesar0301.github.io.git~" _config.yml
install:
- npm run generate
script:
- npm run deploy
env:
  global:
    secure: 1Jv5Y65IWY2fY38dhIuLpEVjOkSJ1xQ50zO4IoMx6RgEWq+2pltEavZ3Ah1955QHAsXlwsRyFh0TesAjQvbwq3eAwwh0bN9kvtowUwOWcFpbcmkD8UUBJ7OgtFkd9kSoKi92aqnWyyIIW7bb1ZNVIXdhvAuZm4CUGIwOjhgebpyf1chKFond/a6pejjQXumWCXRLNyECV4zoEYgR+btsNMUT5gFpA0xFb1ZVTDH+4D78QrMpt7ki+ARnh2bzCoNMQjiSc/5rGKpsOQyb0m8gyEwg73qJ70y72Fxxt8EXh2l2hqvhtTcSYS9FypjxSsqwbfgkcV4skS1pq8hOj4ADXXU4YEMYAA8swfr+GEBinEwVIBeKvfQrgSofPRMlcS4wFyyLfZZU2KK1LAPKjBAdw5Y675RqC+ce0KwGamxxSMjUNl5dDhPHIXgIc8ZJ1YwjCV1KvFzhKvGxgVcVRtkg5lIt3e8ksZuq1VNqjuWzmPdTj7Z5NIcRCZpBWozSJdXtGvXh4QxI2ENUQlKaW0DOIzMP7HCBKWaSA+YwerB+mbm+KFSQvbdLcu9QZISJhwBoqi5Dvw73PGahVQXgZYjXKeoUF6JBPuD6CqHDAJIbqlkLVzCytWoyuHU0Ug8YxwTs+jhIhy20VhzWyN0UV+quTJwxGokHu4pbsPKxgLJ9aUs=
