language: node_js
node_js:
  - '6'
branches:
  only:
  - site-source
before_install:
  - npm install
before_script:
  - export COMMIT_SHA=`git rev-parse --verify HEAD`
  - git clone https://github.com/klugjo/hexo-theme-alpha-dust themes/alpha-dust
  - cp themes/alpha-dust_config.yml themes/alpha-dust/_config.yml
  - git config --global user.name 'xiaming.chen'
  - git config --global user.email 'chenxm35@gmail.com'
install:
  - npm run generate
script:
  - bash deploy/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: ec11043d1833
